version: "3.9"
services:
  chat-ia:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
  postgres:
    image: pgvector/pgvector:pg15
    container_name: postgres_pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
